/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as AnimeSlugRouteImport } from './routes/anime.$slug'
import { Route as SeasonSlugRouteImport } from './routes/season.$slug'
import { Route as UpdatesIdRouteImport } from './routes/updates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSlugRoute = AnimeSlugRouteImport.update({
  id: '/anime/$slug',
  path: '/anime/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSlugRoute = SeasonSlugRouteImport.update({
  id: '/season/$slug',
  path: '/season/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIdRoute = UpdatesIdRouteImport.update({
  id: '/updates/$id',
  path: '/updates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRoute
  '/seasons': typeof SeasonsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/season/$slug': typeof SeasonSlugRoute
  '/updates/$id': typeof UpdatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRoute
  '/seasons': typeof SeasonsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/season/$slug': typeof SeasonSlugRoute
  '/updates/$id': typeof UpdatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRoute
  '/seasons': typeof SeasonsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/season/$slug': typeof SeasonSlugRoute
  '/updates/$id': typeof UpdatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/seasons'
    | '/anime/$slug'
    | '/season/$slug'
    | '/updates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/seasons'
    | '/anime/$slug'
    | '/season/$slug'
    | '/updates/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/seasons'
    | '/anime/$slug'
    | '/season/$slug'
    | '/updates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  FeedRoute: typeof FeedRoute
  SeasonsRoute: typeof SeasonsRoute
  AnimeSlugRoute: typeof AnimeSlugRoute
  SeasonSlugRoute: typeof SeasonSlugRoute
  UpdatesIdRoute: typeof UpdatesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$slug': {
      id: '/anime/$slug'
      path: '/anime/$slug'
      fullPath: '/anime/$slug'
      preLoaderRoute: typeof AnimeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$slug': {
      id: '/season/$slug'
      path: '/season/$slug'
      fullPath: '/season/$slug'
      preLoaderRoute: typeof SeasonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$id': {
      id: '/updates/$id'
      path: '/updates/$id'
      fullPath: '/updates/$id'
      preLoaderRoute: typeof UpdatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  FeedRoute: FeedRoute,
  SeasonsRoute: SeasonsRoute,
  AnimeSlugRoute: AnimeSlugRoute,
  SeasonSlugRoute: SeasonSlugRoute,
  UpdatesIdRoute: UpdatesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
