/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAutomationRouteImport } from './routes/admin.automation'
import { Route as AdminCoverageRouteImport } from './routes/admin.coverage'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'
import { Route as AdminWorksRouteImport } from './routes/admin.works'
import { Route as AnimeSlugRouteImport } from './routes/anime.$slug'
import { Route as FeedIdRouteImport } from './routes/feed.$id'
import { Route as SeasonSlugRouteImport } from './routes/season.$slug'
import { Route as UpdatesIdRouteImport } from './routes/updates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoverageRoute = AdminCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksRoute = AdminWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AdminRoute,
} as any)
const AnimeSlugRoute = AnimeSlugRouteImport.update({
  id: '/anime/$slug',
  path: '/anime/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIdRoute = FeedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FeedRoute,
} as any)
const SeasonSlugRoute = SeasonSlugRouteImport.update({
  id: '/season/$slug',
  path: '/season/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIdRoute = UpdatesIdRouteImport.update({
  id: '/updates/$id',
  path: '/updates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRouteWithChildren
  '/seasons': typeof SeasonsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/works': typeof AdminWorksRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/feed/$id': typeof FeedIdRoute
  '/season/$slug': typeof SeasonSlugRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRouteWithChildren
  '/seasons': typeof SeasonsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/works': typeof AdminWorksRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/feed/$id': typeof FeedIdRoute
  '/season/$slug': typeof SeasonSlugRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/feed': typeof FeedRouteWithChildren
  '/seasons': typeof SeasonsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/works': typeof AdminWorksRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/feed/$id': typeof FeedIdRoute
  '/season/$slug': typeof SeasonSlugRoute
  '/updates/$id': typeof UpdatesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/seasons'
    | '/admin/automation'
    | '/admin/coverage'
    | '/admin/review'
    | '/admin/seasons'
    | '/admin/works'
    | '/anime/$slug'
    | '/feed/$id'
    | '/season/$slug'
    | '/updates/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/feed'
    | '/seasons'
    | '/admin/automation'
    | '/admin/coverage'
    | '/admin/review'
    | '/admin/seasons'
    | '/admin/works'
    | '/anime/$slug'
    | '/feed/$id'
    | '/season/$slug'
    | '/updates/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/feed'
    | '/seasons'
    | '/admin/automation'
    | '/admin/coverage'
    | '/admin/review'
    | '/admin/seasons'
    | '/admin/works'
    | '/anime/$slug'
    | '/feed/$id'
    | '/season/$slug'
    | '/updates/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  FeedRoute: typeof FeedRouteWithChildren
  SeasonsRoute: typeof SeasonsRoute
  AnimeSlugRoute: typeof AnimeSlugRoute
  SeasonSlugRoute: typeof SeasonSlugRoute
  UpdatesIdRoute: typeof UpdatesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coverage': {
      id: '/admin/coverage'
      path: '/coverage'
      fullPath: '/admin/coverage'
      preLoaderRoute: typeof AdminCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works': {
      id: '/admin/works'
      path: '/works'
      fullPath: '/admin/works'
      preLoaderRoute: typeof AdminWorksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/anime/$slug': {
      id: '/anime/$slug'
      path: '/anime/$slug'
      fullPath: '/anime/$slug'
      preLoaderRoute: typeof AnimeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$id': {
      id: '/feed/$id'
      path: '/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof FeedIdRouteImport
      parentRoute: typeof FeedRoute
    }
    '/season/$slug': {
      id: '/season/$slug'
      path: '/season/$slug'
      fullPath: '/season/$slug'
      preLoaderRoute: typeof SeasonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$id': {
      id: '/updates/$id'
      path: '/updates/$id'
      fullPath: '/updates/$id'
      preLoaderRoute: typeof UpdatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminCoverageRoute: typeof AdminCoverageRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AdminWorksRoute: typeof AdminWorksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminCoverageRoute: AdminCoverageRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AdminWorksRoute: AdminWorksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FeedRouteChildren {
  FeedIdRoute: typeof FeedIdRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedIdRoute: FeedIdRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  FeedRoute: FeedRouteWithChildren,
  SeasonsRoute: SeasonsRoute,
  AnimeSlugRoute: AnimeSlugRoute,
  SeasonSlugRoute: SeasonSlugRoute,
  UpdatesIdRoute: UpdatesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
