import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const animeTable = sqliteTable("anime", {
  id: text("id").primaryKey(),
  seasonId: text("season_id").notNull(),
  parentAnimeId: text("parent_anime_id"),
  slug: text("slug").notNull().unique(),
  titleZh: text("title_zh").notNull(),
  titleZhSourceUrl: text("title_zh_source_url"),
  titleJa: text("title_ja").notNull(),
  titleEn: text("title_en"),
  synopsis: text("synopsis").notNull(),
  editorialNote: text("editorial_note"),
  yuriKind: text("yuri_kind", { enum: ["canon", "strong", "adjacent"] }).notNull(),
  yuriStatus: text("yuri_status", { enum: ["confirmed", "pending"] }).notNull(),
  status: text("status", { enum: ["airing", "upcoming", "finished", "paused"] }).notNull(),
  premiereAt: text("premiere_at").notNull(),
  episodeCount: integer("episode_count"),
  episodeDurationMin: integer("episode_duration_min"),
  premiereEpisodeCount: integer("premiere_episode_count").notNull(),
  latestVerifiedEpisode: integer("latest_verified_episode"),
  latestEpisodeSourceUrl: text("latest_episode_source_url"),
  latestEpisodeCheckedAt: text("latest_episode_checked_at"),
  studio: text("studio"),
  sourceMaterial: text("source_material"),
  officialUrl: text("official_url"),
  bangumiUrl: text("bangumi_url"),
  officialXUrl: text("official_x_url"),
  coverUrl: text("cover_url"),
  coverSourceUrl: text("cover_source_url"),
  mainCharacterSourceUrl: text("main_character_source_url"),
  mainCharacterExpectedCount: integer("main_character_expected_count"),
  mainCharacterCheckedAt: text("main_character_checked_at"),
  visualTheme: text("visual_theme").notNull(),
  featured: integer("featured", { mode: "boolean" }).notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
